encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:page>", views.page, name="page"),
    path("wiki/<str:entry>", views.Convert_Entry, name="convert_entry"),
    path("edit/<str:edit_page>", views.Edit_Page, name="edit_page"),
    path("search", views.Search, name="search"),
    path("new_page", views.New_Page, name="new_page"),
    path("random_page", views.Random_Page, name="random_page"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

models.py
import os
import datetime
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class User(db.Model):
    __tablename__= "users"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, nullable=False)
    password = db.Column(db.String, nullable=False)

class Book(db.Model):
    __tablename__= "books"
    id = db.Column(db.Integer, primary_key=True)
    isbn = db.Column(db.String, nullable=False)
    title = db.Column(db.String, nullable=False)
    author = db.Column(db.String, nullable=False)
    year = db.Column(db.String, nullable=False)

class Review(db.Model):
    __tablename__= "reviews"
    id = db.Column(db.Integer, primary_key=True)
    book_rating = db.Column(db.Integer, nullable=False)
    book_rating_text = db.Column(db.String, nullable=False)
    book_id = db.Column(db.Integer, db.ForeignKey("books.id"), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    username=db.Column(db.String, nullable=False)

encyclopedia/views.py
from django import forms
from django.forms import Textarea
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.core.files.storage import default_storage
from django.contrib import messages
from collections import Counter
from django.utils.safestring import mark_safe
import re
import markdown2
import random

from . import util

wikis = util.list_entries()

class TitleForm(forms.Form):
    TitleForm = forms.CharField(label="Wiki Title", widget=forms.TextInput(attrs={'size': '40'}))

class ContentForm(forms.Form):
    ContentForm = forms.CharField(label="", widget=forms.Textarea(attrs={'style': 'width: 35em; height:25em;' }))

class EditForm(forms.Form):
    EditForm = forms.CharField(label="Edit Wiki:", widget=forms.Textarea(attrs={'style': 'width: 45em; height:35em;' }))

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
    })

def page(request, page):
    #if request.method=="GET":
    if default_storage.exists(f"entries/{page}.md"):
        return Convert_Entry(request=request, entry=page)
    else:
        return render(request, f"encyclopedia/Error.html", {
            "message": "No Such Wiki Exists."
        })

def Search(request):
    if request.method == "POST":
        query=request.POST.get('q')
        count = 0
        for i in wikis:
            match = re.search(query, i)
            if match is not None:
                count += 1
                result = i
        if count >=1:
            search = page(request=request, page=result)
        else:
            search = render(request, f"encyclopedia/Error.html", {
                "message": f"No Such Wiki for {query} Exists."
            })
        return search

def Convert_Entry(request, entry):
    md_file = util.get_entry(entry)
    converted_file = markdown2.markdown(md_file)
    return render(request, f"encyclopedia/Page_Title.html", {
        "title": entry,
        "content": converted_file
    })

def New_Page(request):
        #new_page_form = form.cleaned_data["new_page_form"]
    if request.method == "POST":
        #title = TitleForm(request.POST)
        #content = request.POST.get('content')
        content_form = ContentForm(request.POST)
        form = TitleForm(request.POST)
        if form.is_valid() and content_form.is_valid():
            title = form.cleaned_data["TitleForm"]
            content = content_form.cleaned_data["ContentForm"]
            print(title)
            print(content)
            count = 0
            for wiki in wikis:
                title_match = re.search(title, wiki)
                if title_match is not None:
                    count += 1
            if count >= 1:
                    messages.error(request, 'Title already exists.')
                    result = HttpResponseRedirect(reverse("encyclopedia:new_page"))
            else:
                    content_string= "# " + title + "\n" + content
                    print(content_string)
                    util.save_entry(title = title, content=content_string)
                    result = Convert_Entry(request=request, entry = title)
            return result

    else:
        return render(request, f"encyclopedia/New_Page.html", {
            "form" : TitleForm(),
            "content_form": ContentForm()
        })

def Random_Page(request):
    random_page = random.choice(wikis)
    return page(request = request, page = random_page)

def Edit_Page(request, edit_page):
    if request.method == "GET":
        initial_data = util.get_entry(edit_page)
        data = {'EditForm' : initial_data}
        form = EditForm(data)
        return render(request, f"encyclopedia/Edit_Page.html", {
            "edit_page": edit_page,
            "form" : form
        })
    if request.method == "POST":
        form = EditForm(request.POST)
        if form.is_valid():
            edited_wiki = form.cleaned_data["EditForm"]
            util.save_entry(title = edit_page, content=edited_wiki)
            #HttpResponseRedirect(reverse("encyclopedia:page", kwargs={'page':edit_page}))
            return Convert_Entry(request=request, entry = edit_page)

encyclopedia/templates/encyclopedia/CSS.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
<h1>CSS</h1>

<p>CSS is a language that can be used to add style to an <a href="/wiki/HTML">HTML</a> page.</p>
{% endblock %}

encyclopedia/templates/encyclopedia/Django.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
<h1>Django</h1>

<p>Django is a web framework written using <a href="/wiki/Python">Python</a> that allows for the design of web applications that generate <a href="/wiki/HTML">HTML</a> dynamically.</p>
{% endblock %}

encyclopedia/templates/encyclopedia/Edit_Page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
  Edit {{ edit_page | safe }}
{% endblock %}

{% block body %}
    <h1>Edit {{edit_page}}</h1>
    <form method="post" id="wikiEditPageForm" action="{% url 'encyclopedia:edit_page' edit_page %}">
      <div class="form-group col-3">
        {% csrf_token %}
        {{ form }}
        <small id="wikiTitleHelp" class="form-text text-muted">Please ensure that your wiki changes are in the proper Markdown syntax.</small>
      </div>
      {% if messages %}
      <div class="messages alert alert-danger" role="alert">
          {% for message in messages %}
          <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
          {% endfor %}
      </div>
      {% endif %}
      <button id="btn_edit_submit" type="submit" class="btn btn-primary">Submit Changes</button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/Error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    <h1>Error</h1>
    {{ message }}
{% endblock %}

encyclopedia/templates/encyclopedia/Git.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
<h1>Git</h1>

<p>Git is a version control tool that can be used to keep track of versions of a software project.</p>

<h2>GitHub</h2>

<p>GitHub is an online service for hosting git repositories.</p>
{% endblock %}

encyclopedia/templates/encyclopedia/HTML.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
<h1>HTML</h1>

<p>HTML is a markup language that can be used to define the structure of a web page. HTML elements include</p>

<ul>
<li>headings</li>
<li>paragraphs</li>
<li>lists</li>
<li>links</li>
<li>and more!</li>
</ul>

<p>The most recent major version of HTML is HTML5.</p>
{% endblock %}

encyclopedia/templates/encyclopedia/New_Page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
  New Page
{% endblock %}

{% block body %}
    <h1>Create a New Page</h1>
    <form method="post" id="wikiNewPageForm" action="{% url 'encyclopedia:new_page' %}">
      <div class="form-group col-3">
        {% csrf_token %}
        {{ form }}
        <small id="wikiTitleHelp" class="form-text text-muted">The title of this wiki must be unique and not in use.</small>
      </div>
      {% if messages %}
      <div class="messages alert alert-danger" role="alert">
          {% for message in messages %}
          <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
          {% endfor %}
      </div>
      {% endif %}
      <div class="form-group col-9">
        <label for="wikiBody">Wiki Content: </label>
        </br>
        {% csrf_token %}
        {{ content_form }}
        <small id="wikiBodyHelp" class="form-text text-muted">Wiki content must be as factual as possible.</small>
      </div>
      <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">I agree to publicly display my wiki content.</label>
      </div>
      <button id="btn_submit" type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/Page_Title.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title | safe }}
{% endblock %}

{% block body %}
    {{ content| safe}}
      <a href="{% url 'encyclopedia:edit_page' title %}" class="btn btn-info btn-sm">
        <span class="glyphicon glyphicon-edit"></span> Edit Wiki
      </a>
{% endblock %}

encyclopedia/templates/encyclopedia/Python.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
<h1>Python</h1>

<p>Python is a programming language that can be used both for writing <strong>command-line scripts</strong> or building <strong>web applications</strong>.</p>
{% endblock %}

encyclopedia/templates/encyclopedia/Search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
  Search
{% endblock %}

{% block body %}
    <h1>Search Results</h1>
    <h2>
      {{ query }}
    </h2>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <a href="{% url 'encyclopedia:page' entry %}"><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
    <body>
      <div class="hero-image">
        <div class="container-fluid">
          <div class="row">
                <div class="sidebar col-lg-2 col-md-3">
                    <h2>Wiki</h2>
                    <form method="post" action="{% url 'encyclopedia:search' %}">
                        {% csrf_token %}
                        <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                    </form>
                    <div>
                        <a href="{% url 'encyclopedia:index' %}">Home</a>
                    </div>
                    <div>
                        <a href="{% url 'encyclopedia:new_page' %}">Create New Page</a>
                    </div>
                    <div>
                        <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                    </div>
                    {% block nav %}
                    {% endblock %}
                </div>
                <div class="main col-lg-10 col-md-9">
                    {% block body %}
                    {% endblock %}
                </div>
          </div>
        </div>
      </div>
    </body>
</html>

templates/BookResult.html
{% extends "layout.html" %}

{% block title %}
    {{Book.title}}
{% endblock %}

{% block body %}
<h1>{{Book.title}}</h1>
    <h5> Book Details: </h5>
    <table id="BookDetails">
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>ISBN</th>
        <th>Publication Year</th>
        <th>Average Rating Statistics</th>
        <th>Number of Ratings Statistics</th>
      </tr>
      <tr>
        <td>{{Book.title}}</td>
        <td>{{Book.author}}</td>
        <td>{{Book.isbn}}</td>
        <td>{{Book.year}}</td>
        <td>{{AverageRating}}</td>
        <td>{{NumberOfRating}}</td>
      </tr>
    </table>

{% if ReviewsExist%}
    <h5 id="OtherUsrHdr">Other Users' Ratings: </h5>
      <table id="BookRatings">
        <tr>
          <th>User</th>
          <th>Rating</th>
          <th>Reason</th>
        </tr>
      {% for review in book_reviews %}
        <tr>
            <td> {{review.username}}</td>
            <td> {{review.book_rating}} </td>
            <td> {{review.book_rating_text}} </td>
        </tr>
        {% endfor %}
      </table>
{% endif %}

{% if RatingExists %}
    <h5>Leave Your Rating Here: </h5>
    <p> On a scale of 1-5, rate this book where 5 is the highest value and 1 is the lowest. This data will help our users decide on their next great read!</p>

  <form method="post">
    <div class="form-row">
      <div class="form-group col-md-2">
        <label for="inputBookRating">Book Rating: </label>
        <select name="inputBookRating" id="inputBookRating" class="form-control">
          <option selected>Choose...</option>
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
        </select>
      </div>
      <div class="form-group col-md-6">
        <label for="inputBookRatingText">Any Additional Thoughts: </label>
        <input name="inputBookRatingText" type="text" class="form-control" id="inputBookRatingText" placeholder="Type in your comments here">
      </div>
      <div class="form-group col-md-2">
        <label for="submit">Submit Your Review: </label>
        <button type="submit" class="form-control btn btn-primary mb-2">Submit</button>
      </div>
    </div>
  </form>
{% endif %}
{% endblock %}

templates/Error.html
{% extends "layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    <h1>Error</h1>
    {{ message }}
{% endblock %}

templates/Register.html
{% extends "layout.html" %}

{% block title %}
    Register
{% endblock %}

{% block body %}

<h1>New User?</h1>

<p>Register below: </p>
<form action="{{ url_for('Register') }}" method="post">
    <div class="form-group">
        <input class="form-control" name="new_usr" placeholder="Username">
    </div>

    <div class="form-group">
        <input class="form-control" name="new_pass" type="password" placeholder="Password">
    </div>

    <div class="form-group">
        <button class="btn btn-primary" type="submit">Register</button>
    </div>

</form>
{% endblock %}

templates/SearchResultList.html
{% extends "layout.html" %}

{% block title %}
    {{resultQuery}}
{% endblock %}

{% block body %}
  <h1>Search Results for: {{resultQuery}}</h1>
    <p> Click on the link below to get more information about this book: </p>
      <ul>
        {% for item in books %}
          <li class="BookListItem">
            <a href="{{url_for('BookId', Book_id=item.id)}}">
              ISBN: {{item.isbn}} for {{item.title}} by {{item.author}}, written {{item.year}}
            </a>
          </li>
        {% endfor %}
      </ul>
{% endblock %}

templates/Success.html
{% extends "layout.html" %}

{% block title %}
    Success!
{% endblock %}

{% block body %}
    <h1>Success!</h1>
    {{ message }} {{username}}!
{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block title %}
    Users
{% endblock %}

<link rel="stylesheet" href="style.css"/>

{% block body %}
{% if session %}
  <h1>{{message}}, {{username}}!</h1>
    <p>Here at GoodReads, we want to ensure that you have all of the resources to pick out your next great read. Don't forget to leave reviews for individual books, and see the reviews made by other people.</p>

{% else %}
  <h1>Welcome to GoodReads</h1>
    <p>Here at GoodReads, we want to ensure that our users have all of the resources to pick out their next great read. After creating an account, users can leave reviews for individual book as well as see reviews on books that others have read. So what are you waiting for? Sign up today!</p>

    <p>Login below: </p>
      <form action="{{ url_for('index') }}" method="post">
          <div class="form-group">
              <input class="form-control" name="usr" placeholder="Username">
          </div>

          <div class="form-group">
              <input class="form-control" name="pass" type="password" placeholder="Password">
          </div>

          <div class="form-group">
              <button class="btn btn-primary" type="submit">Login</button>
          </div>
      </form>

      <p>To create an account click on the Register button below: </p>
        <form class="form-inline" action="{{ url_for('Register')}}" name="Register">
          <button class="btn btn-primary" type="submit">Register</button>
        </form>
{% endif %}
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
          <ul class= "flashes" style="list-style: none;">
          {% for message in messages %}
            <li>{{ message }}</li>
          {% endfor %}
          </ul>
        {% endif %}
        {% endwith %}
    </head>
    <body>
      <nav class="navbar navbar-expand-lg navbar-light" id="NavBar">
        <a class="navbar-brand">GoodReads</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

        <div class="collapse navbar-collapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{{ url_for('index')}}">Home <span class="sr-only">(current)</span></a>
            </li>
          </ul>

          {% if session %}
          <form class="form-inline my-2 my-lg-0" action="{{ url_for('Search')}}" method="post" id="Search">
            <input name="SearchBar" class="form-control mr-sm-2" placeholder="Find a Book" aria-label="Search" type="text">
            <button class="btn btn-outline-success btn-sm" type="submit">Search</button>
          </form>
          {% endif %}

          {% if session %}
          <form class="form-inline" action="{{ url_for('Logout')}}" name="LogOut">
            <button class="btn btn-sm btn-outline-secondary" type="submit">Log Out</button>
          </form>
          {% endif %}
        </div>
      </nav>
      <div class="hero-image">
        <div class="container">
            {% block body %}
            {% endblock %}
        </div>
      </div>

    </body>
</html>